server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/book_store_application_db

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true